### ISSUE TITLE
How to install sponskrub to use it with yt-dlp

### ISSUE THREAD

**Issue by TheJags** [pukkandan/SponSkrub#1]
hi @pukkandan

Many thanks for your work on `yt-dlp` and `sponskrub`. How can I "install" sponskrub to use it with yt-dlp please.

Under description, it says, "You can build `sponskrub` by running `dub build`."

I'm sorry but how and where do I 'run' `dub build`... Should I run it from within `source code 2021.01.24.tar.gz` after downloading it from latest releases?

My OS is Ubuntu MATE 20.10

**Comment by pukkandan** [comment]
Building is for developers. 

To install, simply download the binary provided in the releases and put it either somewhere in your `$PATH` or in the same folder as `yt-dlp`
![image](https://user-images.githubusercontent.com/6623388/109396138-216ef400-7956-11eb-94ec-efa16c512bfb.png)
For windows, you also need to have a 32bit `libcurl.dll` (a copy of which is given in the releases)

> Many thanks for your work on yt-dlp and sponskrub

All the credits for `sponskrub` goes to @faissaloo. There are only a [few minor changes](https://github.com/yt-dlp/SponSkrub#main-changes) in this fork as compared to [the original](https://github.com/faissaloo/SponSkrub) - the main one being that I am providing windows releases while he doesn't want to.

**Comment by TheJags** [comment]
@pukkandan thank you so much for the super quick reply.

I just tried `sponskrub` on a 3-min video, which took a long time to re-encode.

Then I found this GitHub issue regarding `lossless-cut`:

````
https://github.com/faissaloo/SponSkrub/issues/22#issuecomment-778764487
````

Any plan to integrate `lossless-cut` with your fork of `sponskrub`?

Edit: Sponsor part was cut indeed.

**Comment by pukkandan** [comment]
> which took a long time to re-encode.

If your video player supports chapter skipping, I recommend using sponskrub with the `-chapter` flag. This will simply mark the sponsor sections as seperate chapters instead of cutting them out; and therefore doesn't need a re-encode

---

> Any plan to integrate lossless-cut with your fork of sponskrub?

Sadly, no. It is something I also would like to see implemented, but I don't understand the ffmpeg filters enough to even try.
  

Also see the note in the readme:

> PS: I am not familar enough in DLang to add features or resolve issues (unless the issue is specific to this fork). It is probably better to make the request in faissaloo/sponskrub. I will merge any commits made there into this fork.
