### ISSUE TITLE
Version 2021.03.15 cannot fetch SponsorBlock segment data

### ISSUE THREAD

**Issue by andrewjmetzger** [pukkandan/SponSkrub#2]
Version 2021.03.15, as downloaded from the Releases page, cannot connect to the SponsorBlock API to fetch sponsor segment data. However, manually making a request to the API URL works as expected.

Example commands with error:
```powershell
> sponskrub.exe 'U_JlkXTdFD4' input.webm output.webm
Downloading video sponsor data
Couldn't connect to the Sponsorblock API
Nothing to be done.
```

Rebuilding the EXE with `dub` does not fix this issue:

```powershell 
> Set-Location ./path/to/sponskrub/files/
> git show -s
commit 3077602bff10463e5e87af2c8eb95ed285d21336 (HEAD -> master, tag: 3.7.0, origin/master, origin/HEAD)
Author: faissaloo <faissaloo@gmail.com>
Date:   Sat Mar 13 13:00:44 2021 +0000

    Add proxy support #24


> git pull 
Already up to date
> dub build :sponskrub
Performing "debug" build using C:\D\dmd2\windows\bin64\dmd.exe for x86_64.
sponskrub:sponskrub ~master: building configuration "application"...
Linking...

> sponskrub.exe 'U_JlkXTdFD4' input.webm output.webm
Downloading video sponsor data
Couldn't connect to the Sponsorblock API
Nothing to be done.
```

However, the Linux builds work as expected:
```bash
$ ./sponskrub 'U_JlkXTdFD4' input.webm output.webm
Downloading video sponsor data
Surgically removing the shilling...
[libopus @ 0x5572763c90c0] No bit rate set. Defaulting to 96000 bps.
frame=10108 fps= 17 q=0.0 Lsize=   12677kB time=00:05:37.31 bitrate= 307.9kbits/s speed=0.562x
Done!
```

What could be causing this issue?

**Comment by andrewjmetzger** [comment]
Solved: Adding `libcurl.dll` to the directory with sponskrub.exe allows SponSkrub to work as expected.

~~Suggestion: Add warning about libcurl.dll to the README (possibly also add a note to the README for yt-dlp). PR forthcoming.~~

Edit: Never mind, there is a warning about `libcurl.dll` in the README already.

**Comment by pukkandan** [comment]
> Never mind, there is a warning about libcurl.dll in the README already.

Yes, and I've even given it alongside the releases
